#!/bin/bash
set -e

# Garante permissão de execução
chmod +x /usr/bin/easy-print

echo "======================================================"
echo " ✅ EasyPrint instalado com sucesso!"
echo " 🚀 O Daemon já está configurado para iniciar com o sistema."
echo " 🔎 Para começar a usar agora, procure por 'EasyPrint' no"
echo "    menu de aplicativos ou digite 'easy-print' no terminal."
echo "======================================================"

exit 0